sonar.projectKey=johs13_ito-agents-demo_eb9065d1-3609-4cb4-8943-c4acd7c15075
sonar.projectName=ito-agents-demo
sonar.projectVersion=4.0
sonar.sources=src/main/java
sonar.sourceEncoding=UTF-8
sonar.java.source=21
sonar.java.binaries=target/classes
